# Generated by Django 2.1.5 on 2019-02-09 21:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat', models.IntegerField(choices=[(2, 'Wpływ'), (1, 'Płatność stała'), (0, 'Płatność')], default=0)),
            ],
        ),
        migrations.AddField(
            model_name='payment',
            name='info',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Category'),
            preserve_default=False,
        ),
    ]
