# Generated by Django 2.1.5 on 2019-02-09 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='category',
        ),
        migrations.AlterField(
            model_name='category',
            name='cat',
            field=models.IntegerField(choices=[(2, 'Wpływ'), (1, 'Płatność stała'), (0, 'Płatność')], default=0),
        ),
    ]
