# Generated by Django 2.1.5 on 2019-02-21 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20190209_2301'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Title', max_length=120)),
                ('content', models.TextField(default='')),
                ('date', models.DateField(blank=True, null=True)),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='post')),
            ],
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat',
            field=models.IntegerField(choices=[(0, 'Płatność'), (2, 'Wpływ'), (1, 'Płatność stała')], default=0),
        ),
    ]
