# Generated by Django 2.1.5 on 2019-02-23 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20190221_2309'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery', verbose_name='Image')),
                ('post', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='main.Post')),
            ],
        ),
        migrations.AlterField(
            model_name='cat',
            name='cat',
            field=models.IntegerField(choices=[(0, 'Płatność'), (1, 'Płatność stała'), (2, 'Wpływ')], default=0),
        ),
    ]
